//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allot
    {
        public string A { get; set; }
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string City { get; set; }
        public string CityId { get; set; }
        public Nullable<int> EmployeeAddSum { get; set; }
        public Nullable<int> EmployeeServerSum { get; set; }
        public Nullable<int> UserID_ZR { get; set; }
        public Nullable<int> UserID_YG { get; set; }
        public string RealName_ZR { get; set; }
        public string RealName_YG { get; set; }
        public string AllotState { get; set; }
    }
}
