//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class COST_PayGongJiJin
    {
        public int ID { get; set; }
        public int COST_PayRecordStatusID { get; set; }
        public string EmployeeName { get; set; }
        public string CertificateNumber { get; set; }
        public string PaymentSocialMonth { get; set; }
        public int YearMonth { get; set; }
        public Nullable<decimal> Radix { get; set; }
        public Nullable<decimal> PersonCost { get; set; }
        public Nullable<decimal> CompanyCost { get; set; }
        public Nullable<decimal> Total { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int CreateUserID { get; set; }
        public string CreateUserName { get; set; }
        public int BranchID { get; set; }
        public string CertificateNumberSB { get; set; }
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public int EmployeeId { get; set; }
        public string CityId { get; set; }
        public Nullable<decimal> PayFee { get; set; }
    }
}
