//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class COST_CostTable
    {
        public int ID { get; set; }
        public int CostTableType { get; set; }
        public int YearMonth { get; set; }
        public string SerialNumber { get; set; }
        public decimal ChargeCost { get; set; }
        public decimal ServiceCost { get; set; }
        public string Remark { get; set; }
        public int Status { get; set; }
        public int CRM_Company_ID { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int CreateUserID { get; set; }
        public string CreateUserName { get; set; }
        public int BranchID { get; set; }
        public string IsLadderPrice { get; set; }
        public Nullable<int> CreateFrom { get; set; }
        public Nullable<int> Suppler_ID { get; set; }
    }
}
