//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_CompanyPrice_Audit
    {
        public int ID { get; set; }
        public Nullable<int> CRM_CompanyPrice_ID { get; set; }
        public Nullable<int> CRM_Company_Audit_ID { get; set; }
        public Nullable<int> CRM_Company_ID { get; set; }
        public int PRD_Product_ID { get; set; }
        public int PriceType { get; set; }
        public Nullable<decimal> LowestPrice { get; set; }
        public Nullable<decimal> AddPrice { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int CreateUserID { get; set; }
        public string CreateUserName { get; set; }
        public int BranchID { get; set; }
        public int OperateStatus { get; set; }
        public int OperateNode { get; set; }
    }
}
