//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_CompanyLinkMan_Audit
    {
        public int ID { get; set; }
        public Nullable<int> CRM_CompanyLinkMan_ID { get; set; }
        public Nullable<int> CRM_Company_Audit_ID { get; set; }
        public Nullable<int> CRM_Company_ID { get; set; }
        public string LinkManName { get; set; }
        public string Position { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string Remark { get; set; }
        public string IsDefault { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int CreateUserID { get; set; }
        public string CreateUserName { get; set; }
        public int BranchID { get; set; }
        public int OperateStatus { get; set; }
        public int OperateNode { get; set; }
    }
}
