//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_ZD_HY
    {
        public string Code { get; set; }
        public string HYMC { get; set; }
        public string HYQC { get; set; }
        public string ParentCode { get; set; }
        public Nullable<int> NodeLevel { get; set; }
        public string XYBZ { get; set; }
    }
}
