//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeMiddle
    {
        public int Id { get; set; }
        public Nullable<int> InsuranceKindId { get; set; }
        public Nullable<int> CompanyEmployeeRelationId { get; set; }
        public string PaymentBetween { get; set; }
        public Nullable<int> PaymentStyle { get; set; }
        public Nullable<decimal> CompanyBasePayment { get; set; }
        public Nullable<decimal> CompanyPayment { get; set; }
        public Nullable<decimal> EmployeeBasePayment { get; set; }
        public Nullable<decimal> EmployeePayment { get; set; }
        public Nullable<int> PaymentMonth { get; set; }
        public Nullable<int> StartDate { get; set; }
        public Nullable<int> EndedDate { get; set; }
        public int UseBetween { get; set; }
        public string BillId { get; set; }
        public string Remark { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdatePerson { get; set; }
        public string CityId { get; set; }
    }
}
