//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.EmployeeContact = new HashSet<EmployeeContact>();
            this.EmployeeBank = new HashSet<EmployeeBank>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Tag { get; set; }
        public string CertificateType { get; set; }
        public string CertificateNumber { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Attachments { get; set; }
        public string AccountType { get; set; }
        public string Remark { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdatePerson { get; set; }
    
        public virtual ICollection<EmployeeContact> EmployeeContact { get; set; }
        public virtual ICollection<EmployeeBank> EmployeeBank { get; set; }
    }
}
