//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORG_Menu
    {
        public int ID { get; set; }
        public string MenuName { get; set; }
        public int ParentID { get; set; }
        public string MenuUrl { get; set; }
        public string DepartmentScopeAuthority { get; set; }
        public string DepartmentAuthority { get; set; }
        public int NodeLevel { get; set; }
        public int Sort { get; set; }
        public string IsDisplay { get; set; }
        public string XYBZ { get; set; }
    }
}
