//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORG_User
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string LoginName { get; set; }
        public string RName { get; set; }
        public string Sex { get; set; }
        public int ORG_Department_ID { get; set; }
        public int AccountStatus { get; set; }
        public string XYBZ { get; set; }
    }
}
