//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORG_MenuOp
    {
        public string ID { get; set; }
        public int ORG_Menu_ID { get; set; }
        public string MenuOpName { get; set; }
        public Nullable<int> Sort { get; set; }
        public string XYBZ { get; set; }
    }
}
