//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoliceInsurance_Four_Five
    {
        public int ID { get; set; }
        public int PoliceInsuranceID { get; set; }
        public Nullable<int> C_BaseIS { get; set; }
        public Nullable<int> C_BaseDigit { get; set; }
        public Nullable<int> B_BaseIS { get; set; }
        public Nullable<int> B_BaseDigit { get; set; }
        public Nullable<int> C_BearIS { get; set; }
        public Nullable<int> C_BearDigit { get; set; }
        public Nullable<int> C_BearMonth { get; set; }
        public Nullable<int> B_BearIS { get; set; }
        public Nullable<int> B_BearDigit { get; set; }
        public Nullable<int> B_BearMonth { get; set; }
    
        public virtual PoliceInsurance PoliceInsurance { get; set; }
    }
}
