//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoliceInsurance
    {
        public PoliceInsurance()
        {
            this.EmployeeAdd = new HashSet<EmployeeAdd>();
            this.PoliceInsurance_Four_Five = new HashSet<PoliceInsurance_Four_Five>();
            this.PoliceOperationPoliceInsurancePoliceAccountNature = new HashSet<PoliceOperationPoliceInsurancePoliceAccountNature>();
            this.PoliceRejectRelationship = new HashSet<PoliceRejectRelationship>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> InsuranceKindId { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> MaxPayMonth { get; set; }
        public Nullable<int> InsuranceAdd { get; set; }
        public Nullable<int> InsuranceReduce { get; set; }
        public Nullable<decimal> CompanyPercent { get; set; }
        public Nullable<decimal> CompanyLowestNumber { get; set; }
        public Nullable<decimal> EmployeeLowestNumber { get; set; }
        public Nullable<decimal> CompanyHighestNumber { get; set; }
        public Nullable<decimal> EmployeeHighestNumber { get; set; }
        public Nullable<decimal> EmployeePercent { get; set; }
        public string IsDefault { get; set; }
        public string Remark { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdatePerson { get; set; }
    
        public virtual ICollection<EmployeeAdd> EmployeeAdd { get; set; }
        public virtual InsuranceKind InsuranceKind { get; set; }
        public virtual ICollection<PoliceInsurance_Four_Five> PoliceInsurance_Four_Five { get; set; }
        public virtual ICollection<PoliceOperationPoliceInsurancePoliceAccountNature> PoliceOperationPoliceInsurancePoliceAccountNature { get; set; }
        public virtual ICollection<PoliceRejectRelationship> PoliceRejectRelationship { get; set; }
    }
}
