//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoliceOperationPoliceInsurancePoliceAccountNature
    {
        public int PoliceInsuranceId { get; set; }
        public int PoliceOperationId { get; set; }
        public int PoliceAccountNatureId { get; set; }
    
        public virtual PoliceAccountNature PoliceAccountNature { get; set; }
        public virtual PoliceInsurance PoliceInsurance { get; set; }
        public virtual PoliceOperation PoliceOperation { get; set; }
    }
}
