//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoliceAccountNature
    {
        public PoliceAccountNature()
        {
            this.EmployeeAdd = new HashSet<EmployeeAdd>();
            this.PoliceOperationPoliceInsurancePoliceAccountNature = new HashSet<PoliceOperationPoliceInsurancePoliceAccountNature>();
            this.City = new HashSet<City>();
            this.City1 = new HashSet<City>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Style { get; set; }
        public string Remark { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdatePerson { get; set; }
    
        public virtual ICollection<EmployeeAdd> EmployeeAdd { get; set; }
        public virtual ICollection<PoliceOperationPoliceInsurancePoliceAccountNature> PoliceOperationPoliceInsurancePoliceAccountNature { get; set; }
        public virtual ICollection<City> City { get; set; }
        public virtual ICollection<City> City1 { get; set; }
    }
}
