//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.SupplierNatureCity = new HashSet<SupplierNatureCity>();
            this.SupplierLinkMan = new HashSet<SupplierLinkMan>();
            this.SupplierBill = new HashSet<SupplierBill>();
            this.SupplierBankAccount = new HashSet<SupplierBankAccount>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string OrganizationCode { get; set; }
        public string RegisterAddress { get; set; }
        public string OfficeAddress { get; set; }
        public Nullable<int> CustomerServiceId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateUserID { get; set; }
        public string CreateUserName { get; set; }
    
        public virtual ICollection<SupplierNatureCity> SupplierNatureCity { get; set; }
        public virtual ICollection<SupplierLinkMan> SupplierLinkMan { get; set; }
        public virtual ICollection<SupplierBill> SupplierBill { get; set; }
        public virtual ICollection<SupplierBankAccount> SupplierBankAccount { get; set; }
    }
}
