//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierLinkMan
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public string Position { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string Remark { get; set; }
        public string IsDefault { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUserID { get; set; }
        public string CreateUserName { get; set; }
        public string Status { get; set; }
    
        public virtual Supplier Supplier { get; set; }
    }
}
